// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmj7YQQfU0Qn6LF2Jrikx3d5DKgoXTS6Y',
    appId: '1:549457516957:web:b1dfadca68884daf763774',
    messagingSenderId: '549457516957',
    projectId: 'gcx-device-manager',
    authDomain: 'gcx-device-manager.firebaseapp.com',
    databaseURL: 'https://gcx-device-manager-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gcx-device-manager.appspot.com',
    measurementId: 'G-13FLY8T9NR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD22tLr1nOzCeeYIg4JdxJAEKww8K2det0',
    appId: '1:549457516957:android:325d0445a85e6639763774',
    messagingSenderId: '549457516957',
    projectId: 'gcx-device-manager',
    databaseURL: 'https://gcx-device-manager-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gcx-device-manager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaIjt1awd36AZZLbbg-Wl6YXf8JdOPeoo',
    appId: '1:549457516957:ios:1eb5b397c134307c763774',
    messagingSenderId: '549457516957',
    projectId: 'gcx-device-manager',
    databaseURL: 'https://gcx-device-manager-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gcx-device-manager.appspot.com',
    iosClientId: '549457516957-88vd2k8d5mlji21pq7mr8lqki8tireo6.apps.googleusercontent.com',
    iosBundleId: 'com.example.gcxDeviceManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaIjt1awd36AZZLbbg-Wl6YXf8JdOPeoo',
    appId: '1:549457516957:ios:5118ad03385a0144763774',
    messagingSenderId: '549457516957',
    projectId: 'gcx-device-manager',
    databaseURL: 'https://gcx-device-manager-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gcx-device-manager.appspot.com',
    iosClientId: '549457516957-uu87ltj7h8p7ioq9simv3637bkmpqnve.apps.googleusercontent.com',
    iosBundleId: 'com.example.gcxDeviceManager.RunnerTests',
  );
}
